version: '2'

services:
  tx:
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      BITCOIN_HOST: bitcoin
      BITCOIN_RPCUSER: merlin
      BITCOIN_RPCPASSWORD: secret
    command: py.test -v
  bitcoin:
    image: ascribe/bitcoin
    volumes:
      -  ./.bitcoin:/root/.bitcoin
    ports:
      - '18332'
      - '18333'
    command: bitcoind -regtest -printtoconsole
  bdocs:
    build: .
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app/docs
    command: make html
  vdocs:
    image: nginx
    ports:
      - '30083:80'
    volumes:
      - ./docs/build/html:/usr/share/nginx/html
